#!/bin/bash

# Debian/Ubuntu

if [ -e /usr/bin/apt-get ] || [ -e /etc/debian_version ]
then
sudo apt-get --assume-yes install zlib1g
# sudo apt-get --assume-yes install libx264 libx264-dev
sudo apt-get --assume-yes install gstreamer1.0-plugins-bad libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-bad1.0-dev
fi

# RedHat

if [ -e /etc/redhat-release ] || [ -e /usr/bin/yum ]
then
sudo yum --assumeyes install zlib zlib-devel
sudo yum --assumeyes install libx264 libx264-devel
sudo yum --assumeyes install gstreamer-plugins-bad gstreamer-plugins-bad-free-extras gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld
fi

# OpenSuse

if [ -e /etc/SuSE-release ]
then
sudo zypper --non-interactive install zlib zlib-devel
sudo zypper --non-interactive install libx264
sudo zypper --non-interactive install gstreamer-plugins-bad
fi
