#!/bin/bash

# Debian

if [ -e /usr/bin/apt-get ] || [ -e /etc/debian_version ]
then
sudo apt-get --assume-yes install libogg0 libtheora0
sudo apt-get --assume-yes install zlib1g
fi

# RedHat

if [ -e /etc/redhat-release ] || [ -e /usr/bin/yum ]
then
sudo yum --assumeyes install zlib zlib-devel
sudo yum --assumeyes install libogg libogg-devel 
sudo yum --assumeyes install libtheora
fi
